version: "3.7"

services:
  proxy:
    image: caddy:latest
    env_file: mystbin/caddy/.env
    ports:
      - 5555:443/tcp
      - 5556:80/tcp
    volumes:
      - caddy_config:/config
      - caddy_data:/data
      - ./mystbin/caddy/Caddyfile:/etc/caddy/Caddyfile
    container_name: "staging-reverse-proxy"
    networks:
      main:
        ipv4_address: 172.25.0.10
    depends_on:
      - api

  api:
    image: python:3.9.1-buster
    build: mystbin/rest
    volumes:
      - ./mystbin/database/schema.sql:/etc/schema.sql:ro
      - ./mystbin/rest/config.toml:/usr/src/app/config.toml:ro
    container_name: "staging-api"
    networks:
      main:
        ipv4_address: 172.25.0.11
    depends_on:
      - postgres

volumes:
  caddy_data:
  caddy_config:


networks:
  main:
    ipam:
      driver: default
      config:
        - subnet: 172.25.0.0/16