[production-database]
user = "prod-username"
password = "prod-password"
dsn = "postgresql://<user>:<password>@<IPAddress>:<Port>/<Database>"
schema_path = "database/schema.sql"

[staging-database]
user = "staging-username"
password = "staging-password"
dsn = "postgresql://<user>:<password>@<IPAddress>:<Port>/<Database>"
schema_path = "database/schema.sql"

[apps]
discord_application_id = ""
discord_application_secret = ""
google_application_id = ""
google_application_secret = ""
github_application = ""

[site]
base_site = "http://127.0.0.1:8000"

[paste]
character_limit = 300000
file_limit = 5
log_ip = true

[debug]
db = "False"
site = "False"

[ratelimits]
global_limit = "60/minute"
authed_global_limit = "120/minute"
premium_global_limit = "360/minute"
postpastes = "5/minute"
authed_postpages = "10/minute"
premium_postpastes = "20/minute"
getpaste = "20/minute"
authed_getpaste = "40/minute"
premium_getpaste = "80/minute"
deletepaste = "1/minute"
authed_deletepaste = "10/minute"
premium_deletepaste = "20/minute"
self = "20/minute"
tokengen = "2/hour"
admin = "5/second"