[production-database]
user = "prod-username"
password = "prod-password"
dsn = "postgresql://<user>:<password>@<IPAddress>:<Port>/<Database>"
schema_path = "database/schema.sql"

[staging-database]
user = "staging-username"
password = "staging-password"
dsn = "postgresql://<user>:<password>@<IPAddress>:<Port>/<Database>"
schema_path = "database/schema.sql"

[apps]
discord_application_id = ""
discord_application_secret = ""
google_application_id = ""
google_application_secret = ""
github_application = ""

[site]
base_site = "http://127.0.0.1:8000"

[debug]
db = "False"
site = "False"