[database]
# Production Database values. Should be self explanatory.
user = "prod-username"
password = "prod-password"
dsn = "postgresql://<user>:<password>@<IPAddress>:<Port>/<Database>"
schema_path = "database/schema.sql"

[apps]
# Discord application ID and Secret for OAuth2
discord_application_id = ""
discord_application_secret = ""
# Google application ID and Secret for OAuth2
google_application_id = ""
google_application_secret = ""
# Github application for OAuth2.
github_application = ""

[site]
# Base site URL
base_site = "http://127.0.0.1:8000"

[paste]
# Paste limitations
character_limit = 300000
file_limit = 5
log_ip = true

[debug]
# Debug booleans
db = "False"
site = "False"

[sentry]
# Performance and error data via sentry.io. If left blank sentry will be disabled
dsn = ""
# See Sentry docs for more info.
traces_sample_rate = 0.3
discord_webhook = ""

[ratelimits]
# Ratelimit values. Written in the format of `"time/unit"` ("60/minute")
global_limit = "60/minute"
authed_global_limit = "120/minute"
premium_global_limit = "360/minute"
postpastes = "5/minute"
authed_postpages = "10/minute"
premium_postpastes = "20/minute"
getpaste = "20/minute"
authed_getpaste = "40/minute"
premium_getpaste = "80/minute"
deletepaste = "1/minute"
authed_deletepaste = "10/minute"
premium_deletepaste = "20/minute"
self = "20/minute" #?
tokengen = "2/hour"
admin = "5/second"
apps = "5/hour"
sentry = "10/minute"