name: Lint Code Base

on:
  push:
    branches-ignore: [main]
  pull_request:
    branches: [main]


jobs:
  linter:
    name: Lint Code Base
    runs-on: ubuntu-latest

    steps:
      - name: Checkout source
        uses: actions/checkout@v2

      - name: Lint
        uses: github/super-linter@v3
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          DEFAULT_BRANCH: main
          VALIDATE_PYTHON_PYLINT: true
          VALIDATE_PYTHON_isort: true
