name: Lint Code Base

on:
  push:
    branches-ignore: [main]
  pull_request:
    branches: [main]


jobs:
  backend-lint:
    name: Lint Backend
    runs-on: ubuntu-latest

    steps:
      - name: Checkout source
        uses: actions/checkout@v3

      - name: Run linter
        uses: github/super-linter/slim@v4
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          DEFAULT_BRANCH: master
          VALIDATE_ALL_CODEBASE: true
          VALIDATE_PYTHON_BLACK: true
          VALIDATE_PYTHON_ISORT: true
          LINTER_RULES_PATH: /
          PYTHON_BLACK_CONFIG_FILE: pyproject.toml
          PYTHON_ISORT_CONFIG_FILE: pyproject.toml


  frontend-lint:
    name: Lint frontend
    runs-on: ubuntu-latest

    steps:
      - name: Checkout source
        uses: actions/checkout@v2

      - name: Set up Yarn
        uses: actions/setup-node@v1
        with:
          node-version: "12.0"
      - run: yarn install
        working-directory: ./mystbin/frontend

      - name: Run linters
        uses: wearerequired/lint-action@v1
        with:
          github_token: ${{ secrets.github_token }}
          # Enable linters
          auto_fix: true
          git_name: PythonistaGuild Linter
          # eslint: true
          # eslint_dir: ./mystbin/frontend/
          # eslint_extensions: js,ts,jsx,tsx
          prettier: true
          prettier_dir: ./mystbin/frontend/
          prettier_extensions: js,ts,jsx,tsx
